In [2]:
from pandas_datareader import data
import datetime
from bokeh.plotting import figure, show, output_file
#from bokeh.embed import components
#from bokeh.resources import CDN
#from pandas.util.testing import assert_frame_equal

company_name="Apple"
name="AAPL"
start=datetime.datetime(2020,1,1)
end = datetime.datetime(2020,4,6)

#DateReader("Company_stock_symbol", data_source, start_date, end_date)
df = data.DataReader(name,data_source="yahoo",start=start,end=end)

def status(c, o):
    if c > o:
        value="increase"
    elif c < o:
        value="decrease"
    else:
        value="equal"
    return value
    
df["status"] = [status(c,o) for c,o in zip(df.Close, df.Open)]
df["middle"] = (df.Open+df.Close)/2
df["height"] = abs(df.Close - df.Open)
df

,High,Low,Open,Close,Volume,Adj Close,status,middle,height
Date,,,,,,,,,
2019-12-31,293.679993,289.519989,289.929993,293.649994,25201400.0,292.954712,increase,291.789993,3.720001
2020-01-02,300.600006,295.190002,296.239990,300.350006,33870100.0,299.638885,increase,298.294998,4.110016
2020-01-03,300.579987,296.500000,297.149994,297.429993,36580700.0,296.725769,increase,297.289993,0.279999
2020-01-06,299.959991,292.750000,293.790009,299.799988,29596800.0,299.090149,increase,296.794998,6.009979
2020-01-07,300.899994,297.480011,299.839996,298.390015,27218000.0,297.683533,decrease,299.115005,1.449982
...,...,...,...,...,...,...,...,...,...
2020-03-31,262.489990,252.000000,255.600006,254.289993,49250500.0,254.289993,decrease,254.945000,1.310013
2020-04-01,248.720001,239.130005,246.500000,240.910004,44054600.0,240.910004,decrease,243.705002,5.589996
2020-04-02,245.149994,236.899994,240.339996,244.929993,41483500.0,244.929993,increase,242.634995,4.589996
2020-04-03,245.699997,238.970001,242.800003,241.410004,32470000.0,241.410004,decrease,242.105003,1.389999
2020-04-06,263.109985,249.380005,250.899994,262.470001,50289700.0,262.470001,increase,256.684998,11.570007

In [ ]:
p=figure(x_axis_type='datetime', width=1500, height=500)
p.title.text  = "Helo"

p.rect(df.index[df.Close > df.Open], df.middle, hours_12, abs(df.Open - df.Close))

output_file("cs.html")
show(p)